[package]
name = "pop-mpc-aio"
version = "0.1.0"
edition = "2021"

[dependencies]
pop-mpc-core = { path="../pop-mpc-core" }
tokio = { version="1.17", features=["net","macros","rt"] }
async-trait = "0.1.52"
prost = "0.9"
tokio-tungstenite = "0.17.1"
futures-util = "0.3.21"
bytes = "1.1.0"
