[package]
name = "pop-mpc-aio"
version = "0.1.0"
edition = "2021"

[lib]
name = "mpc_aio"

[features]
default = ["ss"]
ss = ["p256"]

[dependencies]
pop-mpc-core = { path = "../mpc-core" }
tokio = { version = "1.17", features = [
    "net",
    "macros",
    "rt",
    "rt-multi-thread",
] }
async-trait = "0.1.52"
prost = "0.9"
tokio-tungstenite = "0.17.1"
futures-util = "0.3.21"
aes = { version = "0.7.5", features = [] }
cipher = "0.3"
rand = "0.8.5"
rand_core = "0.6.3"
rand_chacha = "0.3.1"
p256 = { version = "0.10.1", optional = true }
