[package]
name = "share-conversion-aio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = ["dep:serde"]

[dependencies]
tlsn-mpc-aio = { path = "../mpc-aio" }
tlsn-mpc-core = { path = "../mpc-core" }
share-conversion-core = { path = "../share-conversion-core" }
tlsn-utils-aio.workspace = true
async-trait.workspace = true
thiserror.workspace = true
rand.workspace = true
rand_chacha.workspace = true
futures.workspace = true
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
tokio.workspace = true
