[package]
name = "tlsn-utils-aio"
version = "0.1.0"
edition = "2021"

[lib]
name = "utils_aio"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1.1.0"
prost = "0.9"
tokio-util = { version = "0.7.1", features = ["codec"] }
async-tungstenite = { version = "0.16" }
futures = "0.3"
futures-util = "0.3"
