[package]
name = "tlsn-tls-2pc-aio"
version = "0.1.0"
edition = "2021"

[lib]
name = "tls_2pc_aio"

[dependencies]
tlsn-tls-2pc-core = { path = "../tls-2pc-core" }
tlsn-tls-core = { path = "../tls-core" }
tlsn-tls-client = { path = "../tls-client" }
tlsn-mpc-aio.workspace = true
tlsn-mpc-circuits.workspace = true
tlsn-utils-aio.workspace = true

async-trait.workspace = true
thiserror.workspace = true
futures.workspace = true
p256.workspace = true
rand.workspace = true

[dev-dependencies]
tlsn-mpc-aio = { workspace = true, features = ["mock"] }
tlsn-utils-aio = { workspace = true, features = ["duplex"] }

tokio.workspace = true
criterion = { workspace = true, features = ["async", "async_tokio"] }

[[bench]]
name = "prf"
harness = false
