[package]
name = "actor-mux"
version = "0.1.0"
edition = "2021"

[features]
default = ["mock", "yamux"]
mock = []
yamux = []

[dependencies]
tlsn-utils-aio = { path = "../../utils/utils-aio" }
async-trait = "0.1"
futures = "0.3"
tokio = { version = "1.23", features = ["time"] }
xtra = { git = "https://github.com/Restioson/xtra", rev = "ca061b4", features = [
    "macros",
    "tokio",
], default-features = false }
yamux = "0.10"

[dev-dependencies]
tokio-util = { version = "0.7", features = ["compat"] }
tokio = { features = ["macros", "io-util", "rt", "rt-multi-thread"] }
