name: Rust

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse

jobs:
  integration-tests:
    if: ( ! github.event.pull_request.draft )
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Nightly with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - name: "Check formatting"
        run: cargo +nightly fmt --check --all --manifest-path integration-tests/Cargo.toml

      - name: Stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.0.0

      - name: "Build"
        run: cargo build --release --manifest-path integration-tests/Cargo.toml

      - name: "Test"
        run: cargo test --release --tests --manifest-path integration-tests/Cargo.toml

  build_and_test:
    if: ( ! github.event.pull_request.draft )
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - uid-mux
          - actors/actor-ot
          - mpc
          - cipher
          - universal-hash
          - aead
          - key-exchange
          - point-addition
          - prf
          - tls
          - utils
    steps:
      - uses: actions/checkout@v3

      - name: Nightly with rustfmt
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          components: rustfmt

      - name: "Check formatting"
        run: cargo +nightly fmt --check --all --manifest-path ${{ matrix.package }}/Cargo.toml

      - name: Stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v2.0.0

      - name: "Build"
        run: cargo build --manifest-path ${{ matrix.package }}/Cargo.toml

      - name: "Test"
        run: cargo test --lib --bins --tests --examples --workspace --manifest-path ${{ matrix.package }}/Cargo.toml

      - name: "Integration Test"
        if: ( ${{ matrix.package}} === "integration-tests" )
        run: cargo test --release --tests --manifest-path ${{ matrix.package }}/Cargo.toml

